include_guard()

macro(set_platform PLATFORM)
	string(TOLOWER "${PLATFORM}" PLATFORM_LOWER)
	string(TOUPPER "${PLATFORM}" PLATFORM_UPPER)

	set(PLATFORM "${PLATFORM_LOWER}" CACHE INTERNAL "" FORCE)
	set(PLATFORM_LOWER "${PLATFORM_LOWER}" CACHE INTERNAL "" FORCE)
	set(PLATFORM_UPPER "${PLATFORM_UPPER}" CACHE INTERNAL "" FORCE)

	set(${PLATFORM_UPPER} TRUE)
endmacro()
